// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCswgPy6hiU22lApwkUBU_TzzDRa1S-48',
    appId: '1:741053167787:web:10b7b8155ad8f869001fee',
    messagingSenderId: '741053167787',
    projectId: 'myapp-38e17',
    authDomain: 'myapp-38e17.firebaseapp.com',
    storageBucket: 'myapp-38e17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5mvoXsKl5S1UnlIeZc0oj-GkcgAfBq6s',
    appId: '1:741053167787:android:c96648ca670e69a0001fee',
    messagingSenderId: '741053167787',
    projectId: 'myapp-38e17',
    storageBucket: 'myapp-38e17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Q4jE6j8xi-QWNcmrn8E7Pm1KqPKWU1E',
    appId: '1:741053167787:ios:5fd083e626ccac43001fee',
    messagingSenderId: '741053167787',
    projectId: 'myapp-38e17',
    storageBucket: 'myapp-38e17.appspot.com',
    iosBundleId: 'com.example.myflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Q4jE6j8xi-QWNcmrn8E7Pm1KqPKWU1E',
    appId: '1:741053167787:ios:5fd083e626ccac43001fee',
    messagingSenderId: '741053167787',
    projectId: 'myapp-38e17',
    storageBucket: 'myapp-38e17.appspot.com',
    iosBundleId: 'com.example.myflutterapp',
  );
}
